# --> check the build file
- src/build_DB.txt:
    - description: Ensure that the file src/build_DB.txt exists
      check: ConfirmFileExists
    - description: Complete all TODOs and remove the TODO markers in the file src/build_DB.txt
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the file src/build_DB.txt
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# --> check the Py file
- src/myDBMS.py:
    - description: Ensure that the file src/myDBMS.py exists
      check: ConfirmFileExists
    - description: Complete all TODOs and remove the TODO markers in the file src/myDBMS.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the file src/myDBMS.py
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# --> check the reflections file
- writing/reflection.md:
    - description: Ensure that the file writing/reflection.md exists
      check: ConfirmFileExists
    - description: Complete all TODOs and remove the TODO markers in the file writing/reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the file writing/reflection.md
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# --> check that the number of commits in the Git repository is beyond a threshold
- description: Have at least a specific minimum number of commits (3) in repository
  check: CountCommits
  options:
    count: 3
